[package]
name = "tecs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# hibitset = "0.6.3"
# rand = "0.8.5"
bevy_utils = "0.10.1"
